FROM node:18.20.4-alpine3.20

WORKDIR /app

COPY package*.json ./
# COPY scripts/init.sh /app/scripts/init.sh

# RUN chmod +x /app/scripts/init.sh
RUN npm install

COPY . .

EXPOSE 3333

# CMD ["sh", "-c", "./scripts/init.sh"]
CMD ["sh", "-c", "npm run dev"]