services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - api-solid:/var/lib/postgresql/data
    networks:
      - api_solid
  
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://docker:docker@api-solid-pg:5432/apisolid?schema=public
    ports:
      - "3333:3333"
    depends_on:
      - api-solid-pg
    volumes:
      - .:/app
    command: ["sh", "-c", "npm run dev"]
    networks:
      - api_solid

volumes:
  api-solid:

networks:
  api_solid:
    driver: bridge