
services:
  web:
    build:
      context: .
    ports:
      - "3333:3333"
    networks:
      - fit-api
    depends_on:
      - postgres
    environment:
      - .env

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - fit-api
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pg123
      POSTGRES_USER: user
      POSTGRES_DB: user

volumes:
  postgres-vol:

networks:
  fit-api:
    driver: bridge
