
services:
  app:
    build: .
    image: fitmealapi-api
    ports:
      - "3333:3333"
    networks:
      - fit_net
    depends_on:
      - postgres
    environment:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:16.2-alpine3.18
    ports:
      - "5432:5432"
    networks:
      - fit_net
    volumes:
      - fit_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  fit_data:

networks:
  fit_net:
    driver: bridge
